In [5]:
import numpy as np # numpy 라이브러리 :시간측정 코딩테스트의 경우 유리하다!

첫번째밭 = [
    [1,0,0,0,0],
    [0,0,1,0,1],
    [0,0,1,0,1],
    [0,0,1,0,1],
    [0,0,1,0,1]
]

두번째밭 = [
    [0,0,0,0,1],
    [0,0,0,0,3],
    [0,0,0,0,4],
    [0,2,0,0,2],
    [4,5,0,2,0]
]

In [7]:
# np.rot90 배열을 반시계방향으로 90도로 회전시킨다. 
# 시계방향으로 돌리려는 경우 -1을 넣는다.
np.rot90(두번째밭, 1) + np.array(첫번째밭) # 반시계방향으로 90도 회전시킨 두번째밭과 첫번째밭을 더한다.


array([[2, 3, 4, 2, 0],
       [0, 0, 1, 0, 3],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 2, 6],
       [0, 0, 1, 0, 5]])

In [9]:
np.rot90(두번째밭,1) - np.array(첫번째밭) #반시계방향으로 90도 회전시킨 두번째밭에서 첫번째밭을 뺀다
# 음수 결과값은 이 문제에서 정답이 되기 어렵다고 판단됨.(패스~)

array([[ 0,  3,  4,  2,  0],
       [ 0,  0, -1,  0,  1],
       [ 0,  0, -1,  0, -1],
       [ 0,  0, -1,  2,  4],
       [ 0,  0, -1,  0,  3]])

In [11]:
np.array(첫번째밭) - np.rot90(두번째밭,1) #첫번째밭에서 반시계방향으로 90도 회전시킨 두번째밭을 뺀다.
# 음수 결과값은 이 문제에서 정답이 되기 어렵다고 판단됨.(패스~)

array([[ 0, -3, -4, -2,  0],
       [ 0,  0,  1,  0, -1],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  1, -2, -4],
       [ 0,  0,  1,  0, -3]])

In [13]:
np.array(첫번째밭) * np.rot90(두번째밭,1) #첫번째밭에서 반시계방향으로 90도 회전시킨 두번째밭을 곱한다.

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 4]])

In [16]:
np.array(첫번째밭) @ np.rot90(두번째밭,1) #첫번째밭에서 반시계방향으로 90도 회전시킨 두번째밭을 행렬의 곱셈을 한다
# 행렬의 곱셈 : https://m.blog.naver.com/PostView.nhn?blogId=junhyuk7272&logNo=50128686426&proxyReferer=https:%2F%2Fwww.google.com%2F

array([[1, 3, 4, 2, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4]])

In [19]:
정답 = np.rot90(두번째밭, 1) + np.array(첫번째밭) 


In [21]:
''.join([str(i) for i in 정답[0]])

'23420'

In [24]:
int(''.join([str(i) for i in 정답[0]]),8)

10000

In [26]:
chr(int(''.join([str(i) for i in 정답[1]]),8))

'C'

In [29]:
for k in range(5):
    print(chr(int(''.join([str(i) for i in 정답[k]]),8)))
    
# 10000, CAVE 니까 만장굴 이라고 유추하게 됨 (문제상에서~)

✐
C
A
V
E


In [31]:
# numpy를 사용하지 않고 하나하나 풀어서 풀어보기~~~ 

In [47]:
sample = [
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
]

첫번째밭 = [
    [1,0,0,0,0],
    [0,0,1,0,1],
    [0,0,1,0,1],
    [0,0,1,0,1],
    [0,0,1,0,1]
]

두번째밭 = [
    [0,0,0,0,1],
    [0,0,0,0,3],
    [0,0,0,0,4],
    [0,2,0,0,2],
    [4,5,0,2,0]
]

In [36]:
x = [[None]*5]*5
x

[[None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None]]

In [39]:
x[0][0] = 1000
x
# 왜 맨왼쪽의 x[0][0]만 바뀌는게 아니라 다 바뀌지? ==> 같은 주소를 갖고 있기 때문...
# x = [[None]*5]*5 에서 *이 그렇게 되게 했던것... 곱셈을 할때는 주의해야함!


[[1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None]]

In [40]:
두번째밭 = [
    [0,0,0,0,1],
    [0,0,0,0,3],
    [0,0,0,0,4],
    [0,2,0,0,2],
    [4,5,0,2,0]
]

In [44]:
#numpy 없이 직접 행렬을 회전시키려면?
# 0,4 -> 0,0
# 1,4 -> 0,1
# 2,4 -> 0,2
# 3,4 -> 0,3
# 4,4 -> 0,4

# 0,3 -> 1,0
# 1,3 -> 1,1
# 2,3 -> 1,2
# 3,3 -> 1,3
# 4,3 -> 1,4

# 0,2 -> 2,0
# 1,2 -> 2,1
# 2,2 -> 2,2
# 3,2 -> 2,3
# 4,2 -> 2,4

# 0,1 -> 1,0
# 1,1 -> 1,1
# 2,1 -> 1,2
# 3,1 -> 1,3
# 4,1 -> 1,4


# 0,0 -> 4,0
# 1,0 -> 4,1
# 2,0 -> 4,2
# 3,0 -> 4,3
# 4,0 -> 4,4

#이렇게 순회하려면 어떻게 해야할까?

In [49]:
for i in range(len(두번째밭)):
    for j in range(len(두번째밭[0])):
        sample[i][j] = 두번째밭[j][len(두번째밭)-1-i] # 5번째값이 없어서 len(두번째값)에서 -1을 하고 난후 -i를 한것
    
sample  # 90도 반시계방향으로 회전시킨 두번째밭 행렬이 됨
        

[[1, 3, 4, 2, 0],
 [0, 0, 0, 0, 2],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 2, 5],
 [0, 0, 0, 0, 4]]

In [51]:
for i in range(len(두번째밭)):
    for j in range(len(두번째밭[0])):
        sample[i][j] += 첫번째밭[i][j]

sample

[[3, 3, 4, 2, 0],
 [0, 0, 2, 0, 4],
 [0, 0, 2, 0, 2],
 [0, 0, 2, 2, 7],
 [0, 0, 2, 0, 6]]